name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - sit

jobs:
  deploy:
    name: Deploy backend to EB
    runs-on: ubuntu-latest
    env:
      GITHUB_ENVIRONMENT: ${{ github.ref == 'refs/heads/sit' && 'SIT' || 'Prod' }}
    environment: ${{ vars.GITHUB_ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Copy all project files except node_modules
        run: rsync -av --exclude='node_modules' ./ ./

      # TODO: uncomment if needed for migration
      # - name: Set DATABASE_URL
      #   run: |
      #     echo "DATABASE_URL=postgres://${{ vars.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_NAME }}?ssl=${{ vars.DB_SSL }}" >> $GITHUB_ENV

      # - name: Run blog and FAQ migration
      #   run: node scripts/blogfaqinsert.js
      #   env:
      #     DATABASE_URL: ${{ vars.DATABASE_URL }}

      - name: Zip project
        run: zip -r deploy.zip . -x "*.git*"

      - name: Set EB app and environment
        run: |
          echo "APP_NAME=${{ vars.APP_NAME }}" >> $GITHUB_ENV
          echo "ENV_NAME=${{ vars.ENV_NAME }}" >> $GITHUB_ENV

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.APP_NAME }}
          environment_name: ${{ vars.ENV_NAME }}
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
